server:
  port: 8080
  context-path: /springboot

girl:
  name: B
  age: 18
  content: name:${name},age:${age}

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.1.90:3306/db_nono?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8
    data-username: yanfa
    data-password: yanfa#123
  jpa:
    database: mysql
    show-sql: false
    hibernate:
      ddl-auto: update

